name: Ejecutar Scheduler Diario

on:
  schedule:
    - cron: '0 0 * * *'  # Esto es medianoche (hora UTC)
  workflow_dispatch:      # Este botón nos permite probarlo a mano ahora

jobs:
  ejecutar-escaneo:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código del repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar librerías
        run: |
          pip install -r requirements.txt

      - name: Ejecutar el Scheduler
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python scheduler.py
